# application.yml
server:
  port: ${PORT:8082}
  servlet:
    context-path: "/producao/v1"

spring:
  application:
    name: producao-microservice
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
    hikari:
      connectionTimeout: 60000 #Tempo que a aplicação vai esperar até que o banco esteja dispponível
      initializationFailTimeout: -1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${DB_DIALECT}

backend:
  pedido:
    url: ${PEDIDO_URL:http://localhost:8080/lanchonete/v1/pedidos}

# swagger-ui and api-docs custom path
springdoc:
  swagger-ui:
    path: "/swagger-ui"
  api-docs:
    path: "/api-docs"